### PR TITLE
Get EIP712Domain without verifying contract if not provided

### PR DESCRIPTION
**Pull request by james-toussaint**

### CODE REVIEW

**Review by mcornaton — APPROVED** [review]
LGTM, thanks :)

**Review by zguesmi — COMMENTED** [review]
Thanks for the quick fix.
We need to update it [here](https://github.com/iExecBlockchainComputing/iexec-common/blob/develop/src/main/java/com/iexec/common/chain/eip712/EIP712Domain.java#L44) also.

**Comment by zguesmi** [comment]
I suggest we also add `@Deprecated` to this class so we have an explicit warning.

**Review by zguesmi — APPROVED** [review]
Perfect, thansk!

**Pull request merged**
